// <auto-generated />
using System;
using System.Collections.Generic;
using LLMCostControl.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LLMCostControl.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CostTrackerDbContext))]
    [Migration("20260626131600_UpdateModelPricingIndex")]
    partial class UpdateModelPricingIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LLMCostControl.Domain.Budgets.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("LLMCostControl.Domain.Budgets.GroupBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("period");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Amount", "LLMCostControl.Domain.Budgets.GroupBudget.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "Period")
                        .IsUnique();

                    b.ToTable("group_budgets", (string)null);
                });

            modelBuilder.Entity("LLMCostControl.Domain.Budgets.GroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CallerId")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("caller_id");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CallerId");

                    b.HasIndex("GroupId", "CallerId")
                        .IsUnique();

                    b.ToTable("group_memberships", (string)null);
                });

            modelBuilder.Entity("LLMCostControl.Domain.Budgets.UserBudgetOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallerId")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("caller_id");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("period");

                    b.Property<DateTimeOffset>("SetAt")
                        .HasColumnType("timestamp with time zone");

                    b.ComplexProperty<Dictionary<string, object>>("Amount", "LLMCostControl.Domain.Budgets.UserBudgetOverride.Amount#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CallerId", "Period")
                        .IsUnique();

                    b.ToTable("user_budget_overrides", (string)null);
                });

            modelBuilder.Entity("LLMCostControl.Domain.Pricing.ModelPricing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("StaleSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.ComplexProperty<Dictionary<string, object>>("Prices", "prices", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal?>("CacheRead")
                                .HasPrecision(18, 8)
                                .HasColumnType("numeric(18,8)")
                                .HasColumnName("price_cache_read");

                            b1.Property<decimal?>("CacheWrite")
                                .HasPrecision(18, 8)
                                .HasColumnType("numeric(18,8)")
                                .HasColumnName("price_cache_write");

                            b1.Property<decimal>("Input")
                                .HasPrecision(18, 8)
                                .HasColumnType("numeric(18,8)")
                                .HasColumnName("price_input");

                            b1.Property<decimal>("Output")
                                .HasPrecision(18, 8)
                                .HasColumnType("numeric(18,8)")
                                .HasColumnName("price_output");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Provider", "Model")
                        .IsUnique();

                    b.ToTable("model_pricing", (string)null);
                });

            modelBuilder.Entity("LLMCostControl.Domain.Usage.UsageEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BudgetSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("CallerId")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("caller_id");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at");

                    b.Property<decimal>("CostAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("cost_amount");

                    b.Property<string>("CostCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("cost_currency");

                    b.Property<Guid?>("EffectiveGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("effective_group_id");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("period");

                    b.Property<decimal>("RunningSpendAfter")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("running_spend_after");

                    b.Property<long>("TokensCacheRead")
                        .HasColumnType("bigint")
                        .HasColumnName("tokens_cache_read");

                    b.Property<long>("TokensCacheWrite")
                        .HasColumnType("bigint")
                        .HasColumnName("tokens_cache_write");

                    b.Property<long>("TokensInput")
                        .HasColumnType("bigint")
                        .HasColumnName("tokens_input");

                    b.Property<long>("TokensOutput")
                        .HasColumnType("bigint")
                        .HasColumnName("tokens_output");

                    b.ComplexProperty<Dictionary<string, object>>("UnitPrices", "unit_prices", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal?>("CacheRead")
                                .HasPrecision(18, 8)
                                .HasColumnType("numeric(18,8)")
                                .HasColumnName("unit_price_cache_read");

                            b1.Property<decimal?>("CacheWrite")
                                .HasPrecision(18, 8)
                                .HasColumnType("numeric(18,8)")
                                .HasColumnName("unit_price_cache_write");

                            b1.Property<decimal>("Input")
                                .HasPrecision(18, 8)
                                .HasColumnType("numeric(18,8)")
                                .HasColumnName("unit_price_input");

                            b1.Property<decimal>("Output")
                                .HasPrecision(18, 8)
                                .HasColumnType("numeric(18,8)")
                                .HasColumnName("unit_price_output");
                        });

                    b.HasKey("EventId");

                    b.HasIndex("CapturedAt");

                    b.HasIndex("CallerId", "Period");

                    b.ToTable("usage_events", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
